=== HARSHITA-VERMA-2147249/CAT1/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Company">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Emp-id" type="xs:integer"/>
							<xs:element name="Emp-name" type="xs:string"/>
							<xs:element name="Emp-age" type="xs:integer"/>
							<xs:element name="Emp-salary" type="MySalary"/>
							<xs:element name="Emp-emailid" type="xs:string"/>
							<xs:element name="Emp-phonenum" type="xs:integer"/>
							<xs:element name="Emp-designation" type="xs:string"/>
						</xs:sequence>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="MySalary">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="50000"/>
    	<xs:maxExclusive value="200000"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== HARSHITA-VERMA-2147249/CAT1/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="medical.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="employee.xsd">
	<Employee>
		<Emp-id>0952</Emp-id>
		<Emp-name>Aakash</Emp-name>
		<Emp-age>45</Emp-age>
		<Emp-salary>77000</Emp-salary>
		<Emp-emailid>aakash@gmail.com</Emp-emailid>
		<Emp-phonenum>9811036529</Emp-phonenum>
		<Emp-designation>Head</Emp-designation>
   </Employee>
   
   <Employee>
		<Emp-id>1740</Emp-id>
		<Emp-name>Isha</Emp-name>
		<Emp-age>60</Emp-age>
		<Emp-salary>55000</Emp-salary>
		<Emp-emailid>isha@gmail.com</Emp-emailid>
		<Emp-phonenum>9811128929</Emp-phonenum>
		<Emp-designation>Team Leader</Emp-designation>
   </Employee>
   
   <Employee>
		<Emp-id>0543</Emp-id>
		<Emp-name>Alisha</Emp-name>
		<Emp-age>45</Emp-age>
		<Emp-salary>76000</Emp-salary>
		<Emp-emailid>98alisha@gmail.com</Emp-emailid>
		<Emp-phonenum>8110291387</Emp-phonenum>
		<Emp-designation>Technical</Emp-designation>
   </Employee>
   
   <Employee>
		<Emp-id>6409</Emp-id>
		<Emp-name>Dhoni</Emp-name>
		<Emp-age>32</Emp-age>
		<Emp-salary>70000</Emp-salary>
		<Emp-emailid>dhoni98@gmail.com</Emp-emailid>
		<Emp-phonenum>7606307612</Emp-phonenum>
		<Emp-designation>Developer</Emp-designation>
   </Employee>
   
   <Employee>
		<Emp-id>419</Emp-id>
		<Emp-name>Ramesh</Emp-name>
		<Emp-age>51</Emp-age>
		<Emp-salary>90000</Emp-salary>
		<Emp-emailid>ramesh568@gmail.com</Emp-emailid>
		<Emp-phonenum>723087612</Emp-phonenum>
		<Emp-designation>Software Enginner</Emp-designation>
   </Employee>
   
    <Employee>
		<Emp-id>578</Emp-id>
		<Emp-name>Virat</Emp-name>
		<Emp-age>29</Emp-age>
		<Emp-salary>120000</Emp-salary>
		<Emp-emailid>virat.76@gmail.com</Emp-emailid>
		<Emp-phonenum>7601109612</Emp-phonenum>
		<Emp-designation>Manager</Emp-designation>
   </Employee>
   
    <Employee>
		<Emp-id>0839</Emp-id>
		<Emp-name>Rupali</Emp-name>
		<Emp-age>50</Emp-age>
		<Emp-salary>65000</Emp-salary>
		<Emp-emailid>rupali123@gmail.com</Emp-emailid>
		<Emp-phonenum>7601635292</Emp-phonenum>
		<Emp-designation>Associate Project Manager</Emp-designation>
   </Employee>
   
    <Employee>
		<Emp-id>309</Emp-id>
		<Emp-name>Suresh Raina</Emp-name>
		<Emp-age>41</Emp-age>
		<Emp-salary>89000</Emp-salary>
		<Emp-emailid>rainasuresh10@gmail.com</Emp-emailid>
		<Emp-phonenum>9601697342</Emp-phonenum>
		<Emp-designation>Leader</Emp-designation>
   </Employee>
   
   <Employee>
		<Emp-id>4920</Emp-id>
		<Emp-name>Preeti</Emp-name>
		<Emp-age>65</Emp-age>
		<Emp-salary>100000</Emp-salary>
		<Emp-emailid>preeti984@gmail.com</Emp-emailid>
		<Emp-phonenum>8931607342</Emp-phonenum>
		<Emp-designation>Developer</Emp-designation>
   </Employee>

</Company>
